#ifndef FOXY_TOKEN_H
    #define FOXY_TOKEN_H

    typedef enum FOXY_TOKEN {
        FOXY_TOKEN_FUNCTION,
        FOXY_TOKEN_CLASS,
        FOXY_TOKEN_FROM,
        FOXY_TOKEN_STRUCT,
        FOXY_TOKEN_ENUM,
        FOXY_TOKEN_EXPORT,
        FOXY_TOKEN_USE,
        FOXY_TOKEN_OVERRULE,
        FOXY_TOKEN_SUPER,
        FOXY_TOKEN_SELF,
        FOXY_TOKEN_FOR,
        FOXY_TOKEN_IF,
        FOXY_TOKEN_SWITCH,
        FOXY_TOKEN_CASE,
        FOXY_TOKEN_DEFAULT,
        FOXY_TOKEN_BREAK,
        FOXY_TOKEN_RETURN,
        FOXY_TOKEN_INCLUDE,
        FOXY_TOKEN_PRIVATE,
        FOXY_TOKEN_PROTECTED,
        FOXY_TOKEN_PUBLIC
    } FOXY_TOKEN;

    typedef enum FOXY_TOKEN_TYPE {
        FOXY_TOKEN_TYPE_CHAR,
        FOXY_TOKEN_TYPE_INT,
        FOXY_TOKEN_TYPE_NUMBER,
        FOXY_TOKEN_TYPE_FLOAT,
        FOXY_TOKEN_TYPE_DOUBLE,
        FOXY_TOKEN_TYPE_LONG,
        FOXY_TOKEN_TYPE_LONG_LONG,
        FOXY_TOKEN_TYPE_UNSIGNED_LONG_LONG,
        FOXY_TOKEN_TYPE_OBJECT,
        FOXY_TOKEN_TYPE_CLASS,
        FOXY_TOKEN_TYPE_DICT,
        FOXY_TOKEN_TYPE_STRUCT,
        FOXY_TOKEN_TYPE_FUNCTION
    } FOXY_TOKEN_TYPE;

    typedef enum FOXY_TOKEN_IDENTIFIER {
        FOXY_TOKEN_IDENTIFIER_NAME,
        FOXY_TOKEN_IDENTIFIER_CHAR,               // TOKEN_CHAR_LITERAL -> opera cuando se usa '' unicamente.
        FOXY_TOKEN_IDENTIFIER_NUMBER,             // TOKEN_NUMBER_LITERAL
        FOXY_TOKEN_IDENTIFIER_INT,                // TOKEN_INT_LITERAL
        FOXY_TOKEN_IDENTIFIER_FLOAT,              // TOKEN_FLOAT_LITERAL
        FOXY_TOKEN_IDENTIFIER_DOUBLE,             // TOKEN_DOUBLE_LITERAL
        FOXY_TOKEN_IDENTIFIER_LONG,               // TOKEN_LONG_LITERAL
        FOXY_TOKEN_IDENTIFIER_LONG_LONG,          // TOKEN_LONG_LONG_LITERAL
        FOXY_TOKEN_IDENTIFIER_UNSIGNED_LONG_LONG, // TOKEN_UNSIGNED_LONG_LONG_LITERAL
        FOXY_TOKEN_IDENTIFIER_CHAR_ARRAY,         // TOKEN_CHAR_ARRAY_LITERAL -> operar cuando se usa "" unicamente.
    } FOXY_TOKEN_IDENTIFIER;

    typedef enum FOXY_TOKEN_OPERATOR {
        FOXY_TOKEN_OPERATOR_ASSIGN,
        FOXY_TOKEN_OPERATOR_ADD,
        FOXY_TOKEN_OPERATOR_SUB,
        FOXY_TOKEN_OPERATOR_MUL,
        FOXY_TOKEN_OPERATOR_DIV,
        FOXY_TOKEN_OPERATOR_POW,
        FOXY_TOKEN_OPERATOR_ARROW,
        FOXY_TOKEN_OPERATOR_DOT,
        FOXY_TOKEN_OPERATOR_HASH,
        FOXY_TOKEN_OPERATOR_COLON,
        FOXY_TOKEN_OPERATOR_SEMICOLON,
        FOXY_TOKEN_OPERATOR_COMMA,
        FOXY_TOKEN_OPERATOR_LPAREN,
        FOXY_TOKEN_OPERATOR_RPAREN,
        FOXY_TOKEN_OPERATOR_LBRACE,
        FOXY_TOKEN_OPERATOR_RBRACE,
        FOXY_TOKEN_OPERATOR_LBRACKET,
        FOXY_TOKEN_OPERATOR_RBRACKET,
        FOXY_TOKEN_OPERATOR_LAMBDA,
        FOXY_TOKEN_OPERATOR_ELLIPSIS,
    } FOXY_TOKEN_OPERATOR;

    typedef enum FOXY_TOKEN_FLAGGED_METHOD {
        FOXY_TOKEN_FLAGGED_METHOD_NEW,          // __new (Constructor estilo Lua)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_TOSTRING,     // __tostring[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_ADD,          // __add (+)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_SUB,          // __sub (-)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_MUL,          // __mul (*)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_DIV,          // __div (/)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_POW,          // __pow (**)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_BAND,         // __band (&)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_BOR,          // __bor (|)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_BNOT,         // __bnot (~)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_BXOR,         // __bxor (^)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_LSHIFT,       // __lshift (<<)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_RSHIFT,       // __rshift (>>)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_CLOSED,       // __closed (Garbage collector / cierre de campo)[cite: 1]
        FOXY_TOKEN_FLAGGED_METHOD_LEN           // __len (#)[cite: 1]
    } FOXY_TOKEN_FLAGGED_METHOD;
#endif