#ifndef FOXY_TOKENS
#define FOXY_TOKENS

typedef enum FOXY_TOKEN {
    FOXY_TOKEN_FUNCTION,
    FOXY_TOKEN_CLASS,
    FOXY_TOKEN_FROM,
    FOXY_TOKEN_STRUCT,
    FOXY_TOKEN_ENUM,
    FOXY_TOKEN_EXPORT,
    FOXY_TOKEN_USE,
    FOXY_TOKEN_OVERRULE,
    FOXY_TOKEN_SUPER,
    FOXY_TOKEN_SELF,
    FOXY_TOKEN_FOR,
    FOXY_TOKEN_IF,
    FOXY_TOKEN_SWITCH,
    FOXY_TOKEN_CASE,
    FOXY_TOKEN_DEFAULT,
    FOXY_TOKEN_BREAK,
    FOXY_TOKEN_RETURN,
    FOXY_TOKEN_INCLUDE,
    FOXY_TOKEN_PRIVATE,
    FOXY_TOKEN_PROTECTED,
    FOXY_TOKEN_PUBLIC
} FOXY_TOKEN;

typedef enum FOXY_TOKENTYPE {
    FOXY_TOKEN_TYPE_CHAR,
    FOXY_TOKEN_TYPE_INT,
    FOXY_TOKEN_TYPE_NUMBER,
    FOXY_TOKEN_TYPE_FLOAT,
    FOXY_TOKEN_TYPE_DOUBLE,
    FOXY_TOKEN_TYPE_LONG,
    FOXY_TOKEN_TYPE_LONG_LONG,
    FOXY_TOKEN_TYPE_UNSIGNED_LONG_LONG,
    FOXY_TOKEN_TYPE_OBJECT,
    FOXY_TOKEN_TYPE_CLASS,
    FOXY_TOKEN_TYPE_DICT,
    FOXY_TOKEN_TYPE_STRUCT,
    FOXY_TOKEN_TYPE_FUNCTION
} FOXY_TOKENTYPE;

typedef struct FOXY_TOKEN_LITERAL {
    FOXY_TOKEN_IDENTIFIER_NAME,
    FOXY_TOKEN_IDENTIFIER_NUMBER,             // TOKEN_NUMBER_LITERAL
    FOXY_TOKEN_IDENTIFIER_INT,                // TOKEN_INT_LITERAL
    FOXY_TOKEN_IDENTIFIER_FLOAT,              // TOKEN_FLOAT_LITERAL
    FOXY_TOKEN_IDENTIFIER_DOUBLE,             // TOKEN_DOUBLE_LITERAL
    FOXY_TOKEN_IDENTIFIER_LONG,               // TOKEN_LONG_LITERAL
    FOXY_TOKEN_IDENTIFIER_LONG_LONG,          // TOKEN_LONG_LONG_LITERAL
    FOXY_TOKEN_IDENTIFIER_UNSIGNED_LONG_LONG, // TOKEN_UNSIGNED_LONG_LONG_LITERAL
    FOXY_TOKEN_IDENTIFIER_CHAR_ARRAY,         // TOKEN_CHAR_ARRAY_LITERAL -> operar cuando se usa "" unicamente.
    FOXY_TOKEN_IDENTIFIER_
} FOXY_TOKEN_LITERAL;


#endif