#pragma once

#include "f_settings.h"
#include <stdint.h>
#include <stddef.h>

/* ========================================================================= */
/* LISTA MAESTRA DE FOXCODES (FOXY_FOXCODE_LIST)                             */
/* ========================================================================= */
#if FOXY_COMPILER_SUPPORTS_XMACROS
#define FOXY_FOXCODE_LIST(F) \
    /* 1. CONTROL Y SISTEMA */ \
    F(FOXCODE_CONTROL_NOP) \
    F(FOXCODE_CONTROL_HALT) \
    F(FOXCODE_CONTROL_INCLUDE) \
    F(FOXCODE_CONTROL_GC) \
    F(FOXCODE_EXTRAARG) \
    \
    /* 2. CARGA DE CONSTANTES Y LITERALES */ \
    F(FOXCODE_LOAD_CONST) \
    F(FOXCODE_LOAD_NULL) \
    F(FOXCODE_LOAD_TRUE) \
    F(FOXCODE_LOAD_FALSE) \
    F(FOXCODE_LOAD_INT) \
    \
    /* 3. CONVERSIÓN Y CASTEO DE TIPOS */ \
    F(FOXCODE_CAST) \
    F(FOXCODE_TYPEOF) \
    \
    /* 4. VARIABLES, SCOPES Y ENUMS */ \
    F(FOXCODE_SCOPE_LOAD_LOCAL) \
    F(FOXCODE_SCOPE_STORE_LOCAL) \
    F(FOXCODE_SCOPE_LOAD_GLOBAL) \
    F(FOXCODE_SCOPE_STORE_GLOBAL) \
    F(FOXCODE_SCOPE_LOAD_LIB) \
    F(FOXCODE_SCOPE_USE_ENUM) \
    \
    /* 5. PROPIEDADES, MIEMBROS Y PUNTEROS STRUCT */ \
    F(FOXCODE_GET_MEMBER) \
    F(FOXCODE_SET_MEMBER) \
    F(FOXCODE_GET_MEMBER_PTR) \
    F(FOXCODE_SET_MEMBER_PTR) \
    F(FOXCODE_ADDRESS_OF) \
    \
    /* 6. INDEXACIÓN Y LONGITUD */ \
    F(FOXCODE_GET_INDEX) \
    F(FOXCODE_SET_INDEX) \
    F(FOXCODE_LEN) \
    \
    /* 7. ARITMÉTICA Y COMPARACIONES */ \
    F(FOXCODE_ARITHM_ADD) \
    F(FOXCODE_ARITHM_SUB) \
    F(FOXCODE_ARITHM_MUL) \
    F(FOXCODE_ARITHM_DIV) \
    F(FOXCODE_ARITHM_MOD) \
    F(FOXCODE_ARITHM_POW) \
    F(FOXCODE_ARITHM_NEG) \
    F(FOXCODE_ARITHM_POSTINC) \
    F(FOXCODE_ARITHM_PREINC) \
    F(FOXCODE_ARITHM_POSTDEC) \
    F(FOXCODE_ARITHM_PREDEC) \
    F(FOXCODE_ARITHM_CONCAT) \
    F(FOXCODE_LOGICAL_NOT) \
    F(FOXCODE_LOGICAL_EQ) \
    F(FOXCODE_LOGICAL_NEQ) \
    F(FOXCODE_LOGICAL_LT) \
    F(FOXCODE_LOGICAL_GT) \
    F(FOXCODE_LOGICAL_LE) \
    F(FOXCODE_LOGICAL_GE) \
    \
    /* 8. OPERADORES BITWISE */ \
    F(FOXCODE_BITWISE_AND) \
    F(FOXCODE_BITWISE_OR) \
    F(FOXCODE_BITWISE_XOR) \
    F(FOXCODE_BITWISE_NOT) \
    F(FOXCODE_BITWISE_SHL) \
    F(FOXCODE_BITWISE_SHR) \
    \
    /* 9. CONTROL DE FLUJO Y SALTOS */ \
    F(FOXCODE_FLOWCONTROL_JUMP) \
    F(FOXCODE_FLOWCONTROL_JUMP_IF_FALSE) \
    F(FOXCODE_FLOWCONTROL_JUMP_IF_TRUE) \
    F(FOXCODE_FLOWCONTROL_GOTO_LABEL) \
    F(FOXCODE_FLOWCONTROL_GOTO) \
    F(FOXCODE_FLOWCONTROL_POP) \
    F(FOXCODE_FLOWCONTROL_CALL) \
    F(FOXCODE_FLOWCONTROL_CALL_VARARG) \
    F(FOXCODE_FLOWCONTROL_RET) \
    F(FOXCODE_FLOWCONTROL_SELF_CALL) \
    F(FOXCODE_FLOWCONTROL_SUPER_CALL) \
    \
    /* 10. ITERACIÓN Y CICLOS */ \
    F(FOXCODE_LOOP_FOR_PREP) \
    F(FOXCODE_LOOP_FOR_LOOP) \
    F(FOXCODE_LOOP_ITER_PREP) \
    F(FOXCODE_LOOP_ITER_NEXT) \
    \
    /* 11. CONSTRUCCIÓN DE ESTRUCTURAS Y OBJETOS */ \
    F(FOXCODE_NEW_ARRAY) \
    F(FOXCODE_NEW_DICT) \
    F(FOXCODE_NEW_STRUCT) \
    F(FOXCODE_NEW_CLASS) \
    F(FOXCODE_NEW_OBJECT) \
    F(FOXCODE_METHOD_BIND) \
    F(FOXCODE_INVOKE_META) \
    \
    /* 12. MANEJO DE EXCEPCIONES */ \
    F(FOXCODE_EXCEPTION_THROW) \
    F(FOXCODE_EXCEPTION_TRY_BEGIN) \
    F(FOXCODE_EXCEPTION_TRY_CATCH) \
    F(FOXCODE_EXCEPTION_TRY_EXCEPT) \
    F(FOXCODE_EXCEPTION_TRY_FINAL)

/* Generación del enum empacado usando X-Macros */
#define F(fcode) fcode,
typedef enum FOXY_PACKED {
    FOXY_FOXCODE_LIST(F)
    FOXCODE_COUNT
} FOXY_FOXCODE;
#undef F

typedef FOXY_FOXCODE FoxCode;

#else

typedef enum FOXY_PACKED {
    FOXCODE_CONTROL_NOP = 0,
    FOXCODE_CONTROL_HALT,
    FOXCODE_CONTROL_INCLUDE,
    FOXCODE_CONTROL_GC,
    FOXCODE_EXTRAARG,
    FOXCODE_LOAD_CONST,
    FOXCODE_LOAD_NULL,
    FOXCODE_LOAD_TRUE,
    FOXCODE_LOAD_FALSE,
    FOXCODE_CAST,
    FOXCODE_TYPEOF,
    FOXCODE_SCOPE_LOAD_LOCAL,
    FOXCODE_SCOPE_STORE_LOCAL,
    FOXCODE_SCOPE_LOAD_GLOBAL,
    FOXCODE_SCOPE_STORE_GLOBAL,
    FOXCODE_SCOPE_LOAD_LIB,
    FOXCODE_SCOPE_USE_ENUM,
    FOXCODE_GET_MEMBER,
    FOXCODE_SET_MEMBER,
    FOXCODE_GET_MEMBER_PTR,
    FOXCODE_SET_MEMBER_PTR,
    FOXCODE_ADDRESS_OF,
    FOXCODE_GET_INDEX,
    FOXCODE_SET_INDEX,
    FOXCODE_LEN,
    FOXCODE_ARITHM_ADD,
    FOXCODE_ARITHM_SUB,
    FOXCODE_ARITHM_MUL,
    FOXCODE_ARITHM_DIV,
    FOXCODE_ARITHM_MOD,
    FOXCODE_ARITHM_POW,
    FOXCODE_ARITHM_NEG,
    FOXCODE_ARITHM_POSTINC,
    FOXCODE_ARITHM_PREINC,
    FOXCODE_ARITHM_POSTDEC,
    FOXCODE_ARITHM_PREDEC,
    FOXCODE_LOGICAL_NOT,
    FOXCODE_LOGICAL_EQ,
    FOXCODE_LOGICAL_NEQ,
    FOXCODE_LOGICAL_LT,
    FOXCODE_LOGICAL_GT,
    FOXCODE_LOGICAL_LE,
    FOXCODE_LOGICAL_GE,
    FOXCODE_BITWISE_AND,
    FOXCODE_BITWISE_OR,
    FOXCODE_BITWISE_XOR,
    FOXCODE_BITWISE_NOT,
    FOXCODE_BITWISE_SHL,
    FOXCODE_BITWISE_SHR,
    FOXCODE_FLOWCONTROL_JUMP,
    FOXCODE_FLOWCONTROL_JUMP_IF_FALSE,
    FOXCODE_FLOWCONTROL_JUMP_IF_TRUE,
    FOXCODE_FLOWCONTROL_GOTO_LABEL,
    FOXCODE_FLOWCONTROL_GOTO,
    FOXCODE_FLOWCONTROL_POP,
    FOXCODE_FLOWCONTROL_CALL,
    FOXCODE_FLOWCONTROL_CALL_VARARG,
    FOXCODE_FLOWCONTROL_RET,
    FOXCODE_FLOWCONTROL_SELF_CALL,
    FOXCODE_FLOWCONTROL_SUPER_CALL,
    FOXCODE_LOOP_FOR_PREP,
    FOXCODE_LOOP_FOR_LOOP,
    FOXCODE_LOOP_ITER_PREP,
    FOXCODE_LOOP_ITER_NEXT,
    FOXCODE_NEW_ARRAY,
    FOXCODE_NEW_DICT,
    FOXCODE_NEW_STRUCT,
    FOXCODE_NEW_CLASS,
    FOXCODE_NEW_OBJECT,
    FOXCODE_METHOD_BIND,
    FOXCODE_INVOKE_META,
    FOXCODE_EXCEPTION_THROW,
    FOXCODE_EXCEPTION_TRY_BEGIN,
    FOXCODE_EXCEPTION_TRY_CATCH,
    FOXCODE_EXCEPTION_TRY_EXCEPT,
    FOXCODE_EXCEPTION_TRY_FINAL,
    FOXCODE_COUNT
} FOXY_FOXCODE;

typedef FOXY_FOXCODE FoxCode;

#endif