#ifndef FOXY_TOKEN_H
#define FOXY_TOKEN_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

/* ========================================================================= */
/* 1. CATEGORÍAS PRINCIPALES DE TOKENS (0-15)                                */
/* ========================================================================= */

#define FOXY_TOKEN_CAT_KEYWORD     1
#define FOXY_TOKEN_CAT_TYPE        2
#define FOXY_TOKEN_CAT_IDENTIFIER  3
#define FOXY_TOKEN_CAT_OPERATOR    4
#define FOXY_TOKEN_CAT_METHOD      5
#define FOXY_TOKEN_CAT_LITERAL     6
#define FOXY_TOKEN_CAT_ERROR       7

/* ========================================================================= */
/* 2. LISTAS MAESTRAS COMPLETAS (X-MACROS)                                   */
/* ========================================================================= */

#define FOXY_TOKEN_KEYWORD_LIST(F) \
    F(FOXY_TOKEN_KEYWORD_FUNCTION) \
    F(FOXY_TOKEN_KEYWORD_CLASS) \
    F(FOXY_TOKEN_KEYWORD_FROM) \
    F(FOXY_TOKEN_KEYWORD_STRUCT) \
    F(FOXY_TOKEN_KEYWORD_ENUM) \
    F(FOXY_TOKEN_KEYWORD_EXPORT) \
    F(FOXY_TOKEN_KEYWORD_USE) \
    F(FOXY_TOKEN_KEYWORD_OVERRULE) \
    F(FOXY_TOKEN_KEYWORD_SUPER) \
    F(FOXY_TOKEN_KEYWORD_SELF) \
    F(FOXY_TOKEN_KEYWORD_GOTO) \
    F(FOXY_TOKEN_KEYWORD_WHILE) \
    F(FOXY_TOKEN_KEYWORD_FOR) \
    F(FOXY_TOKEN_KEYWORD_FOREACH) \
    F(FOXY_TOKEN_KEYWORD_IF) \
    F(FOXY_TOKEN_KEYWORD_ELSEIF) \
    F(FOXY_TOKEN_KEYWORD_ELSE) \
    F(FOXY_TOKEN_KEYWORD_SWITCH) \
    F(FOXY_TOKEN_KEYWORD_CASE) \
    F(FOXY_TOKEN_KEYWORD_DEFAULT) \
    F(FOXY_TOKEN_KEYWORD_BREAK) \
    F(FOXY_TOKEN_KEYWORD_RETURN) \
    F(FOXY_TOKEN_KEYWORD_INCLUDE) \
    F(FOXY_TOKEN_KEYWORD_PRIVATE) \
    F(FOXY_TOKEN_KEYWORD_PROTECTED) \
    F(FOXY_TOKEN_KEYWORD_PUBLIC) \
    F(FOXY_TOKEN_KEYWORD_TRY) \
    F(FOXY_TOKEN_KEYWORD_CATCH) \
    F(FOXY_TOKEN_KEYWORD_EXCEPT) \
    F(FOXY_TOKEN_KEYWORD_FINAL) \
    F(FOXY_TOKEN_KEYWORD_TYPEOF)

#define FOXY_TOKEN_TYPE_LIST(F) \
    F(FOXY_TOKEN_TYPE_NULL) \
    F(FOXY_TOKEN_TYPE_BOOL) \
    F(FOXY_TOKEN_TYPE_CHAR) \
    F(FOXY_TOKEN_TYPE_UCHAR) \
    F(FOXY_TOKEN_TYPE_SHORT) \
    F(FOXY_TOKEN_TYPE_USHORT) \
    F(FOXY_TOKEN_TYPE_INT) \
    F(FOXY_TOKEN_TYPE_UINT) \
    F(FOXY_TOKEN_TYPE_LONG) \
    F(FOXY_TOKEN_TYPE_ULONG) \
    F(FOXY_TOKEN_TYPE_LLONG) \
    F(FOXY_TOKEN_TYPE_ULLONG) \
    F(FOXY_TOKEN_TYPE_FLOAT) \
    F(FOXY_TOKEN_TYPE_DOUBLE) \
    F(FOXY_TOKEN_TYPE_LDOUBLE) \
    F(FOXY_TOKEN_TYPE_NUMBER) \
    F(FOXY_TOKEN_TYPE_OBJECT) \
    F(FOXY_TOKEN_TYPE_DICT)

#define FOXY_TOKEN_FLAGGED_METHOD_LIST(F) \
    F(FOXY_TOKEN_FLAGGED_METHOD_NEW) \
    F(FOXY_TOKEN_FLAGGED_METHOD_CAST) \
    F(FOXY_TOKEN_FLAGGED_METHOD_CLOSED) \
    F(FOXY_TOKEN_FLAGGED_METHOD_TOSTRING) \
    F(FOXY_TOKEN_FLAGGED_METHOD_LEN) \
    F(FOXY_TOKEN_FLAGGED_METHOD_ADD) \
    F(FOXY_TOKEN_FLAGGED_METHOD_SUB) \
    F(FOXY_TOKEN_FLAGGED_METHOD_MUL) \
    F(FOXY_TOKEN_FLAGGED_METHOD_DIV) \
    F(FOXY_TOKEN_FLAGGED_METHOD_MOD) \
    F(FOXY_TOKEN_FLAGGED_METHOD_POW) \
    F(FOXY_TOKEN_FLAGGED_METHOD_UNM) \
    F(FOXY_TOKEN_FLAGGED_METHOD_NOT) \
    F(FOXY_TOKEN_FLAGGED_METHOD_EQ) \
    F(FOXY_TOKEN_FLAGGED_METHOD_NEQ) \
    F(FOXY_TOKEN_FLAGGED_METHOD_LT) \
    F(FOXY_TOKEN_FLAGGED_METHOD_GT) \
    F(FOXY_TOKEN_FLAGGED_METHOD_LE) \
    F(FOXY_TOKEN_FLAGGED_METHOD_GE) \
    F(FOXY_TOKEN_FLAGGED_METHOD_BAND) \
    F(FOXY_TOKEN_FLAGGED_METHOD_BOR) \
    F(FOXY_TOKEN_FLAGGED_METHOD_BNOT) \
    F(FOXY_TOKEN_FLAGGED_METHOD_BXOR) \
    F(FOXY_TOKEN_FLAGGED_METHOD_LSHIFT) \
    F(FOXY_TOKEN_FLAGGED_METHOD_RSHIFT) \
    F(FOXY_TOKEN_FLAGGED_METHOD_FOREACH)

#define FOXY_TOKEN_LITERAL_LIST(F) \
    F(FOXY_TOKEN_LIT_BOOL) \
    F(FOXY_TOKEN_LIT_CHAR) \
    F(FOXY_TOKEN_LIT_STRING) \
    F(FOXY_TOKEN_LIT_INT_I) \
    F(FOXY_TOKEN_LIT_UINT_UI) \
    F(FOXY_TOKEN_LIT_LONG_L) \
    F(FOXY_TOKEN_LIT_ULONG_UL) \
    F(FOXY_TOKEN_LIT_LLONG_LL) \
    F(FOXY_TOKEN_LIT_ULLONG_ULL) \
    F(FOXY_TOKEN_LIT_FLOAT_F) \
    F(FOXY_TOKEN_LIT_DOUBLE_D) \
    F(FOXY_TOKEN_LIT_LDOUBLE_LD) \
    F(FOXY_TOKEN_LIT_NUMBER_N)

#define FOXY_TOKEN_OPERATOR_LIST(F) \
    F(FOXY_TOKEN_OPERATOR_ASSIGN) \
    F(FOXY_TOKEN_OPERATOR_ADD) \
    F(FOXY_TOKEN_OPERATOR_SUB) \
    F(FOXY_TOKEN_OPERATOR_MUL) \
    F(FOXY_TOKEN_OPERATOR_DIV) \
    F(FOXY_TOKEN_OPERATOR_MOD) \
    F(FOXY_TOKEN_OPERATOR_POW) \
    F(FOXY_TOKEN_OPERATOR_INC) \
    F(FOXY_TOKEN_OPERATOR_DEC) \
    F(FOXY_TOKEN_OPERATOR_ADD_ASSIGN) \
    F(FOXY_TOKEN_OPERATOR_SUB_ASSIGN) \
    F(FOXY_TOKEN_OPERATOR_MUL_ASSIGN) \
    F(FOXY_TOKEN_OPERATOR_DIV_ASSIGN) \
    F(FOXY_TOKEN_OPERATOR_MOD_ASSIGN) \
    F(FOXY_TOKEN_OPERATOR_AND) \
    F(FOXY_TOKEN_OPERATOR_OR) \
    F(FOXY_TOKEN_OPERATOR_NOT) \
    F(FOXY_TOKEN_OPERATOR_EQ) \
    F(FOXY_TOKEN_OPERATOR_NEQ) \
    F(FOXY_TOKEN_OPERATOR_LT) \
    F(FOXY_TOKEN_OPERATOR_GT) \
    F(FOXY_TOKEN_OPERATOR_LE) \
    F(FOXY_TOKEN_OPERATOR_GE) \
    F(FOXY_TOKEN_OPERATOR_ARROW) \
    F(FOXY_TOKEN_OPERATOR_LAMBDA) \
    F(FOXY_TOKEN_OPERATOR_HASH) \
    F(FOXY_TOKEN_OPERATOR_ELLIPSIS) \
    F(FOXY_TOKEN_OPERATOR_QUESTION) \
    F(FOXY_TOKEN_OPERATOR_LPAREN) \
    F(FOXY_TOKEN_OPERATOR_RPAREN) \
    F(FOXY_TOKEN_OPERATOR_LBRACE) \
    F(FOXY_TOKEN_OPERATOR_RBRACE) \
    F(FOXY_TOKEN_OPERATOR_LBRACKET) \
    F(FOXY_TOKEN_OPERATOR_RBRACKET) \
    F(FOXY_TOKEN_OPERATOR_COMMA) \
    F(FOXY_TOKEN_OPERATOR_SEMICOLON) \
    F(FOXY_TOKEN_OPERATOR_COLON) \
    F(FOXY_TOKEN_OPERATOR_DOT)

/* ========================================================================= */
/* 3. ENUMERADOS ESTÁNDAR                                                   */
/* ========================================================================= */

#define F(name) name,
typedef enum { FOXY_TOKEN_KEYWORD_LIST(F) } FOXY_TOKEN_KEYWORD;
typedef enum { FOXY_TOKEN_TYPE_LIST(F) } FOXY_TOKEN_TYPE;
typedef enum { FOXY_TOKEN_FLAGGED_METHOD_LIST(F) } FOXY_TOKEN_FLAGGED_METHOD;
typedef enum { FOXY_TOKEN_LITERAL_LIST(F) } FOXY_TOKEN_LITERAL;
typedef enum { FOXY_TOKEN_OPERATOR_LIST(F) } FOXY_TOKEN_OPERATOR;
#undef F

/* ========================================================================= */
/* 4. ESTRUCTURA DE TOKEN PORTABLE CON BIT-FIELDS                            */
/* ========================================================================= */

typedef struct {
    const char *filename;
    uint32_t line;
    uint32_t column;
} FoxyLocation;

/**
 * @brief Token individual escaneado por el Lexer.
 */

typedef struct {
    const char *start;          // Puntero directo al texto del lexema
    uint16_t type_category : 4; // Categoría (1-15)
    uint16_t subtype       : 12;// Subtipo del enum (0-4095)
    uint32_t length;            // Longitud del lexema
} FoxyToken;

typedef struct {
    const char *text;           // Texto reservado
    uint16_t category : 4;      // Categoría
    uint16_t subtype  : 12;     // Subtipo asignado
} FoxyKeywordMap;

extern const FoxyKeywordMap FOXY_KEYWORD_TABLE[];
extern const size_t FOXY_KEYWORD_TABLE_SIZE;

#endif // FOXY_TOKEN_H